### ISSUE TITLE
[NodeJs16]  DeprecationWarning: Invalid 'main' field

### ISSUE THREAD

**Issue by alexhaller** [indentjs/objectorarray#7]
Hi,
Since Nodejs 16 I am getting following **DeprecationWarning: Invalid 'main' field in '<pathToApp>\node_modules\objectorarray\package.json' of 'dist/index.js'**. Could you please fix that?
Thank you!
Alexander

**Comment by rdominic** [comment]
Also seeing this.

**Comment by hanszhoou** [comment]
@alexhaller @rdominic 

Fixed by https://github.com/zhouhanseng/objectorarray/commit/d5021ac64ed9147ceaedcb97a1c8156f0143018b.

[endent@2.1.0](https://www.npmjs.com/package/endent) released.

PS. Could you please help me to close this issue, since I lost my 2 factor authentic token, this project has moved to https://github.com/zhouhanseng/objectorarray

**Comment by BRAVO68WEB** [comment]
Same here

```
node - v16.5.0
npm - 7.20.1
```

**Comment by BRAVO68WEB** [comment]
Still not fixed

**Comment by IMMihaylov** [comment]
same here

**Comment by almothafar** [comment]
@zhouhanseng it is still NOT fixed, 1.0.5 here and getting:

```console
(node:423) [DEP0128] DeprecationWarning: Invalid 'main' field in '/home/almothafar/.npm-global/lib/node_modules/cordova/node_modules/objectorarray/package.json' of 'dist/index.js'. Please either fix that or report it to the module a
uthor
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Also why we can't open any issue in your new repo?

**Comment by satyamgchetu** [comment]
(node:1632) [DEP0128] DeprecationWarning: Invalid 'main' field in 'D:\satyamg\react-tsx-electron\node_modules\eslint-config-airbnb-typescript\package.json' of 'dist/eslint-config-airbnb-typescript.js'. Please either
fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)


how to solve this

**Comment by afeurra** [comment]
Just follow the path to the broken package.json and change from
`"main": "dist/index.js",`
to  
`"main": "index.js",`

**Comment by carmcha** [comment]
Go to 
C:\Users\[yourusername]\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\cloudform\package.json

change 
"main": "packages/cloudform/index.js",
to 
"main": "index.js",

**Comment by aniketsingh30** [comment]
Thanks @carmcha. Not getting deprecate warning message  now.

**Comment by aniketsingh30** [comment]
Is there any fix for this **An error occurred during the push operation: Unexpected token 'export'** @carmcha

**Comment by LEOJESUSMENA** [comment]
> Go to C:\Users[yourusername]\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\cloudform\package.json
> 
> change "main": "packages/cloudform/index.js", to "main": "index.js",
This fixed it for me.. Thank you. 
However, I landed here originally because my AppSync is not actually updating the offline data to the cloud, or vice versa, and I thought this could have been the reason. 
I still get no Sync with the cloud. I have run pulls and pushes, as well as amplify update api. 
Anyone who could help??? BTW, I am new to Expo cli and Amplify-aws.
Thanks so much

**Comment by LEOJESUSMENA** [comment]
> Go to C:\Users[yourusername]\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\cloudform\package.json
> 
> change "main": "packages/cloudform/index.js", to "main": "index.js",

This fixed it for me.. Thank you @carmcha !!!!
However, I landed here originally because my AppSync is not actually updating the offline data to the cloud, or viceversa, and I thought this could be the reason. 
I still get no Sync with the cloud. I have run pulls and pushes, as well as amplify update api. 
Anyone who could help??? BTW, I am new to Expo cli and Amplify-aws.
Thanks so much

**Comment by MuhAssar** [comment]
same, getting this error in Cordova iOS app

fixed by changing /dist/index.js to just index.js in package.json of this package

**Comment by meesii** [comment]
Modules that have an invalid main entry (e.g., ./does-not-exist.js) and also have an index.js file in the top level directory will resolve the index.js file. That is deprecated and is going to throw an error in future Node.js versions.

[https://nodejs.org/api/all.html#DEP0128](url)

**Comment by DavLomen** [comment]
reduced node version to 14.6.0

**Comment by the-code-genin** [comment]
Downgrading to node 14 fixed the issue.

**Comment by vaxidovulugbek** [comment]
hi, 
 DeprecationWarning: The URL http://your-proxy-url:your-proxy-port is invalid. Future versions of Node.js will throw an error.
 how to fix this bug ? npm is not worked

**Comment by Foddie2** [comment]
This does not work

**Comment by nhhockeyplayer** [comment]
still does not work as of 2024
okay sorry
its 2025 in 3 hours
